before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
before_script:
  - git clone --depth 1 git://github.com/mauke/unibilium.git
  - make -j2 -C unibilium
  - sudo make -j2 -C unibilium install
  - sudo ldconfig
  - git clone --depth 1 git://github.com/o11c/libtermkey.git -b o11c termkey-c
  - make -j2 -C termkey-c
  - make -j2 -C termkey-c test
  - sudo make -j2 -C termkey-c install
  - sudo ldconfig
script:
  - cargo build -j 2 -v
  - cargo test -j 2 -v
